[package]
name = "readtimestamp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
itertools = "0.12.0"
owo-colors = "3.5.0"
regex = "1.10.2"
time = { version = "0.3.30", features = [
    "formatting",
    "local-offset",
    "macros",
] }
timeago = { version = "0.4.2", features = [] }

[profile.release]
codegen-units = 1
lto = true
strip = true
